### ISSUE TITLE
Error "There is no setup method in options "

### ISSUE THREAD

**Issue by thomasbrodusch** [a145789/vue3-script-to-setup#3]
Hi, thanks for your project!

I've got this error when trying to use yoru package

```shell
tosetup src/MyComponent.vue
File src/MyComponent.vue start of transform... in the src/MyComponent.vue
There is no setup method in options in the src/MyComponent.vue
transform failure in the src/MyComponent.vue
```

How can I fix that?

**Comment by a145789** [comment]
Hello, it appears that there is a missing `setup function` in `MyComponent.vue`. Perhaps `MyComponent.vue` is using the [options](https://vuejs.org/api/options-state.html) syntax? `vue3-script-to-setup` is designed to convert [setup](https://vuejs.org/api/composition-api-setup.html#basic-usage) functions to the setup pattern.

If your code includes a setup function, this might be a bug. You can try it out in the [playground](https://a145789.github.io/vue3-script-to-setup/#code=&codeType=sfc&propsNotOnlyTs=0) and send me the URL, or paste your code here.

If you wish to convert options to the composition API, you can try using [vue2-to-composition-api](https://github.com/wd3322/vue2-to-composition-api).

Lastly, I'd like to remind you that the code generated by conversion tools may not be entirely accurate, so please be sure to carefully review the logic of the code after conversion.

**Comment by a145789** [comment]
If there's no problem, I'll close it, and you can open it at any time
